// Actual products data from backend - matching the real product database
const mockProducts = [
  // TechStore Products (sellerId: 1) - 7 products
  {
    id: 1,
    title: "iPhone 15 Pro",
    name: "iPhone 15 Pro",
    price: 999.99,
    originalPrice: 1099.99,
    category: "smartphones",
    sellerId: 1,
    seller: "TechStore",
    image:
      "https://images.unsplash.com/photo-1556656793-08538906a9f8?w=400&h=300&fit=crop",
    description: "Latest iPhone with advanced features and titanium design",
    rating: 4.8,
    reviewCount: 245,
    views: 12500,
    stock: 50,
    brand: "Apple",
    inStock: true,
    stockQuantity: 50,
    discount: 9,
    sales: 245,
    subcategory: "smartphones",
    features: [
      "A17 Pro chip with 6-core GPU",
      "6.7-inch Super Retina XDR display",
      "Advanced camera system",
      "Titanium design",
      "USB-C connector",
      "All-day battery life",
    ],
    specifications: {
      Display: "6.7-inch Super Retina XDR",
      Processor: "A17 Pro chip",
      Storage: "128GB",
      Camera: "48MP Pro camera system",
      Battery: "All-day battery life",
      "Operating System": "iOS 17",
    },
  },
  {
    id: 2,
    title: "Sony WH-1000XM5 Headphones",
    name: "Sony WH-1000XM5 Headphones",
    price: 349.99,
    originalPrice: 399.99,
    category: "audio",
    sellerId: 1,
    seller: "TechStore",
    image:
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop",
    description: "Industry-leading noise canceling wireless headphones",
    rating: 4.8,
    reviewCount: 189,
    views: 8900,
    stock: 75,
    brand: "Sony",
    inStock: true,
    stockQuantity: 75,
    discount: 13,
    sales: 189,
    subcategory: "audio",
    features: [
      "Industry-leading noise cancellation",
      "30-hour battery life",
      "Premium comfort design",
      "Touch controls",
      "Quick charge support",
      "Hi-Res Audio certified",
    ],
    specifications: {
      Driver: "30mm dynamic",
      Frequency: "4Hz-40,000Hz",
      Battery: "30 hours (NC on)",
      Weight: "250g",
      Connectivity: "Bluetooth 5.2",
      Codecs: "LDAC, AAC, SBC",
    },
  },
  {
    id: 3,
    title: "Samsung Galaxy S24 Ultra",
    name: "Samsung Galaxy S24 Ultra",
    price: 1199.99,
    originalPrice: 1299.99,
    category: "smartphones",
    sellerId: 1,
    seller: "TechStore",
    image:
      "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400&h=300&fit=crop",
    description: "Flagship Android phone with S Pen and AI features",
    rating: 4.7,
    reviewCount: 312,
    views: 15200,
    stock: 40,
    brand: "Samsung",
    inStock: true,
    stockQuantity: 40,
    discount: 8,
    sales: 312,
    subcategory: "smartphones",
    features: [
      "Snapdragon 8 Gen 3 processor",
      "6.8-inch Dynamic AMOLED 2X display",
      "200MP main camera with AI zoom",
      "S Pen integration",
      "AI-powered features",
      "5000mAh battery",
    ],
    specifications: {
      Display: "6.8-inch Dynamic AMOLED 2X",
      Processor: "Snapdragon 8 Gen 3",
      Storage: "256GB",
      Camera: "200MP Main + Ultra Wide + Telephoto",
      Battery: "5000mAh",
      "Operating System": "Android 14 with One UI 6.1",
    },
  },
  {
    id: 4,
    title: "Dell XPS 13 Laptop",
    name: "Dell XPS 13 Laptop",
    price: 1199.99,
    originalPrice: 1399.99,
    category: "laptops",
    sellerId: 1,
    seller: "TechStore",
    image:
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=300&fit=crop",
    description: "Ultra-portable laptop with stunning InfinityEdge display",
    rating: 4.7,
    reviewCount: 203,
    views: 9240,
    stock: 35,
    brand: "Dell",
    inStock: true,
    stockQuantity: 35,
    discount: 14,
    sales: 203,
    subcategory: "laptops",
    features: [
      "13th Gen Intel Core i7 processor",
      "13.4-inch 4K OLED display",
      "16GB LPDDR5 RAM",
      "512GB PCIe SSD",
      "Intel Iris Xe graphics",
      "Thunderbolt 4 ports",
    ],
    specifications: {
      Display: "13.4-inch 4K OLED",
      Processor: "Intel Core i7-1355U",
      Memory: "16GB LPDDR5",
      Storage: "512GB PCIe SSD",
      Graphics: "Intel Iris Xe",
      "Operating System": "Windows 11 Pro",
    },
  },
  {
    id: 5,
    title: "Gaming Mechanical Keyboard RGB",
    name: "Gaming Mechanical Keyboard RGB",
    price: 129.99,
    originalPrice: 159.99,
    category: "gaming",
    sellerId: 1,
    seller: "TechStore",
    image:
      "https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=400&h=300&fit=crop",
    description:
      "RGB backlit mechanical gaming keyboard with Cherry MX switches",
    rating: 4.5,
    reviewCount: 178,
    views: 5420,
    stock: 65,
    brand: "Razer",
    inStock: true,
    stockQuantity: 65,
    discount: 19,
    sales: 178,
    subcategory: "gaming",
    features: [
      "Cherry MX mechanical switches",
      "RGB backlighting with effects",
      "Anti-ghosting technology",
      "Dedicated media keys",
      "Durable aluminum frame",
      "Gaming mode",
    ],
    specifications: {
      "Switch Type": "Cherry MX Red",
      Backlighting: "RGB with effects",
      "Key Layout": "Full-size 104 keys",
      Connection: "USB-C",
      "Polling Rate": "1000Hz",
      Dimensions: "440 x 135 x 36mm",
    },
  },
  {
    id: 6,
    title: "LG 27-inch 4K Monitor",
    name: "LG 27-inch 4K Monitor",
    price: 449.99,
    originalPrice: 549.99,
    category: "monitors",
    sellerId: 1,
    seller: "TechStore",
    image:
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&h=300&fit=crop",
    description: "4K UHD IPS monitor with HDR support for professionals",
    rating: 4.6,
    reviewCount: 156,
    views: 6750,
    stock: 25,
    brand: "LG",
    inStock: true,
    stockQuantity: 25,
    discount: 18,
    sales: 156,
    subcategory: "monitors",
    features: [
      "27-inch 4K UHD IPS panel",
      "HDR10 support",
      "99% sRGB color gamut",
      "USB-C connectivity",
      "Height adjustable stand",
      "AMD FreeSync",
    ],
    specifications: {
      Display: "27-inch 4K UHD IPS",
      Resolution: "3840 x 2160",
      "Color Gamut": "99% sRGB",
      "Refresh Rate": "60Hz",
      "Response Time": "5ms",
      Connectivity: "HDMI, USB-C, DisplayPort",
    },
  },
  {
    id: 7,
    title: "Wireless Gaming Mouse",
    name: "Wireless Gaming Mouse",
    price: 89.99,
    originalPrice: 119.99,
    category: "gaming",
    sellerId: 1,
    seller: "TechStore",
    image:
      "https://images.unsplash.com/photo-1615663235685-4d5ee2ff7b43?w=400&h=300&fit=crop",
    description: "High-precision wireless gaming mouse with RGB lighting",
    rating: 4.4,
    reviewCount: 134,
    views: 4200,
    stock: 80,
    brand: "Logitech",
    inStock: true,
    stockQuantity: 80,
    discount: 25,
    sales: 134,
    subcategory: "gaming",
    features: [
      "25,600 DPI HERO sensor",
      "Wireless with 70-hour battery",
      "RGB lighting with effects",
      "11 programmable buttons",
      "Lightweight design",
      "PowerPlay compatible",
    ],
    specifications: {
      Sensor: "HERO 25K",
      DPI: "100-25,600",
      "Battery Life": "70 hours",
      Buttons: "11 programmable",
      Weight: "80g",
      Connectivity: "LIGHTSPEED wireless",
    },
  },

  // AppleStore Products (sellerId: 2) - 6 products
  {
    id: 8,
    title: "MacBook Air M3",
    name: "MacBook Air M3",
    price: 1299.99,
    originalPrice: 1399.99,
    category: "laptops",
    sellerId: 2,
    seller: "AppleStore",
    image:
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400&h=300&fit=crop",
    description: "Powerful laptop with M3 chip for professionals and creators",
    rating: 4.9,
    reviewCount: 412,
    views: 15600,
    stock: 25,
    brand: "Apple",
    inStock: true,
    stockQuantity: 25,
    discount: 7,
    sales: 412,
    subcategory: "laptops",
    features: [
      "M3 chip with 8-core CPU",
      "13.6-inch Liquid Retina display",
      "Up to 18 hours battery life",
      "8GB unified memory",
      "256GB SSD storage",
      "Two Thunderbolt ports",
    ],
    specifications: {
      Display: "13.6-inch Liquid Retina",
      Processor: "M3 chip with 8-core CPU",
      Memory: "8GB unified memory",
      Storage: "256GB SSD",
      Battery: "Up to 18 hours",
      "Operating System": "macOS Sonoma",
    },
  },
  {
    id: 9,
    title: "iPad Pro 12.9-inch M2",
    name: "iPad Pro 12.9-inch M2",
    price: 1099.99,
    originalPrice: 1199.99,
    category: "tablets",
    sellerId: 2,
    seller: "AppleStore",
    image:
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=300&fit=crop",
    description:
      "Professional tablet with M2 chip and Liquid Retina XDR display",
    rating: 4.8,
    reviewCount: 298,
    views: 11200,
    stock: 40,
    brand: "Apple",
    inStock: true,
    stockQuantity: 40,
    discount: 8,
    sales: 298,
    subcategory: "tablets",
    features: [
      "M2 chip with 8-core CPU",
      "12.9-inch Liquid Retina XDR display",
      "ProRes video recording",
      "Apple Pencil hover",
      "Face ID",
      "5G connectivity",
    ],
    specifications: {
      Display: "12.9-inch Liquid Retina XDR",
      Processor: "M2 chip",
      Storage: "128GB",
      Camera: "12MP Wide + 10MP Ultra Wide",
      Battery: "Up to 10 hours",
      Connectivity: "Wi-Fi 6E + 5G",
    },
  },
  {
    id: 10,
    title: "AirPods Pro (3rd Gen)",
    name: "AirPods Pro (3rd Gen)",
    price: 249.99,
    originalPrice: 279.99,
    category: "audio",
    sellerId: 2,
    seller: "AppleStore",
    image:
      "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=400&h=300&fit=crop",
    description:
      "Active noise cancellation wireless earbuds with spatial audio",
    rating: 4.7,
    reviewCount: 567,
    views: 18900,
    stock: 85,
    brand: "Apple",
    inStock: true,
    stockQuantity: 85,
    discount: 11,
    sales: 567,
    subcategory: "audio",
    features: [
      "Active Noise Cancellation",
      "Transparency mode",
      "Spatial Audio with head tracking",
      "Adaptive EQ",
      "Up to 6 hours listening",
      "MagSafe charging case",
    ],
    specifications: {
      Driver: "Custom high-excursion Apple driver",
      Battery: "Up to 6 hours (with ANC)",
      Charging: "Lightning + MagSafe",
      "Water Resistance": "IPX4",
      Chip: "H2 chip",
      Controls: "Force sensor",
    },
  },
  {
    id: 11,
    title: "Apple Watch Series 9",
    name: "Apple Watch Series 9",
    price: 399.99,
    originalPrice: 429.99,
    category: "wearables",
    sellerId: 2,
    seller: "AppleStore",
    image:
      "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=400&h=300&fit=crop",
    description:
      "Advanced fitness and health tracking with Always-On Retina display",
    rating: 4.6,
    reviewCount: 324,
    views: 13400,
    stock: 55,
    brand: "Apple",
    inStock: true,
    stockQuantity: 55,
    discount: 7,
    sales: 324,
    subcategory: "wearables",
    features: [
      "S9 SiP with 64-bit dual-core processor",
      "Always-On Retina display",
      "Blood oxygen monitoring",
      "ECG app",
      "Double Tap gesture",
      "Water resistant to 50m",
    ],
    specifications: {
      Display: "45mm Always-On Retina",
      Processor: "S9 SiP",
      Battery: "Up to 18 hours",
      "Water Resistance": "50m",
      Connectivity: "GPS, WiFi, Bluetooth",
      Health: "Heart rate, ECG, Blood oxygen",
    },
  },
  {
    id: 12,
    title: "MacBook Pro 14-inch M3",
    name: "MacBook Pro 14-inch M3",
    price: 1999.99,
    originalPrice: 2199.99,
    category: "laptops",
    sellerId: 2,
    seller: "AppleStore",
    image:
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=300&fit=crop",
    description: "Pro laptop with M3 Pro chip for demanding workflows",
    rating: 4.9,
    reviewCount: 187,
    views: 8900,
    stock: 18,
    brand: "Apple",
    inStock: true,
    stockQuantity: 18,
    discount: 9,
    sales: 187,
    subcategory: "laptops",
    features: [
      "M3 Pro chip with 11-core CPU",
      "14.2-inch Liquid Retina XDR display",
      "Up to 22 hours battery life",
      "18GB unified memory",
      "512GB SSD storage",
      "Three Thunderbolt 4 ports",
    ],
    specifications: {
      Display: "14.2-inch Liquid Retina XDR",
      Processor: "M3 Pro chip",
      Memory: "18GB unified memory",
      Storage: "512GB SSD",
      Battery: "Up to 22 hours",
      Ports: "3x Thunderbolt 4, HDMI, SDXC",
    },
  },
  {
    id: 13,
    title: "iPhone 14 Pro Max",
    name: "iPhone 14 Pro Max",
    price: 899.99,
    originalPrice: 1099.99,
    category: "smartphones",
    sellerId: 2,
    seller: "AppleStore",
    image:
      "https://images.unsplash.com/photo-1678911820864-e2c567c655d7?w=400&h=300&fit=crop",
    description:
      "Previous generation iPhone with Dynamic Island and pro cameras",
    rating: 4.7,
    reviewCount: 456,
    views: 16800,
    stock: 30,
    brand: "Apple",
    inStock: true,
    stockQuantity: 30,
    discount: 18,
    sales: 456,
    subcategory: "smartphones",
    features: [
      "A16 Bionic chip",
      "6.7-inch Super Retina XDR display",
      "Dynamic Island",
      "Pro camera system",
      "Always-On display",
      "Action mode video",
    ],
    specifications: {
      Display: "6.7-inch Super Retina XDR",
      Processor: "A16 Bionic chip",
      Storage: "128GB",
      Camera: "48MP Main + 12MP Ultra Wide + 12MP Telephoto",
      Battery: "Up to 29 hours video",
      "Operating System": "iOS 17",
    },
  },

  // ShoesWorld Products (sellerId: 3) - 6 products
  {
    id: 14,
    title: "Nike Air Jordan 1 Retro High",
    name: "Nike Air Jordan 1 Retro High",
    price: 179.99,
    originalPrice: 200.0,
    category: "footwear",
    sellerId: 3,
    seller: "ShoesWorld",
    image:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop",
    description:
      "Classic basketball shoes with iconic silhouette and premium leather",
    rating: 4.7,
    reviewCount: 445,
    views: 22100,
    stock: 100,
    brand: "Nike",
    inStock: true,
    stockQuantity: 100,
    discount: 10,
    sales: 445,
    subcategory: "footwear",
    features: [
      "Premium leather upper",
      "Air-Sole unit in heel",
      "Rubber outsole with pivot circle",
      "Perforations for breathability",
      "Iconic Wings logo",
      "High-top silhouette",
    ],
    specifications: {
      Upper: "Premium leather",
      Sole: "Rubber with Air-Sole unit",
      Closure: "Lace-up",
      Height: "High-top",
      Weight: "1.2 lbs",
      Style: "Basketball/Lifestyle",
    },
  },
  {
    id: 15,
    title: "Adidas Ultraboost 22",
    name: "Adidas Ultraboost 22",
    price: 149.99,
    originalPrice: 180.0,
    category: "footwear",
    sellerId: 3,
    seller: "ShoesWorld",
    image:
      "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400&h=300&fit=crop",
    description: "Premium running shoes with Boost midsole technology",
    rating: 4.7,
    reviewCount: 378,
    views: 16700,
    stock: 85,
    brand: "Adidas",
    inStock: true,
    stockQuantity: 85,
    discount: 17,
    sales: 378,
    subcategory: "footwear",
    features: [
      "Boost midsole technology",
      "Primeknit+ upper",
      "Continental rubber outsole",
      "ARAMIS heel construction",
      "Energy return",
      "Responsive cushioning",
    ],
    specifications: {
      Midsole: "Boost foam",
      Upper: "Primeknit+ textile",
      Outsole: "Continental rubber",
      Drop: "10mm",
      Weight: "10.9 oz",
      Use: "Running",
    },
  },
  {
    id: 16,
    title: "Converse Chuck Taylor All Star",
    name: "Converse Chuck Taylor All Star",
    price: 59.99,
    originalPrice: 75.0,
    category: "footwear",
    sellerId: 3,
    seller: "ShoesWorld",
    image:
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=300&fit=crop",
    description: "Classic canvas sneakers with timeless design",
    rating: 4.4,
    reviewCount: 289,
    views: 8900,
    stock: 150,
    brand: "Converse",
    inStock: true,
    stockQuantity: 150,
    discount: 20,
    sales: 289,
    subcategory: "footwear",
    features: [
      "Canvas upper",
      "Rubber toe cap",
      "Metal eyelets",
      "All Star ankle patch",
      "Vulcanized rubber sole",
      "Iconic silhouette",
    ],
    specifications: {
      Upper: "Canvas",
      Sole: "Vulcanized rubber",
      Closure: "Lace-up",
      Height: "High-top",
      Weight: "1.1 lbs",
      Style: "Casual/Lifestyle",
    },
  },
  {
    id: 17,
    title: "Vans Old Skool Classic",
    name: "Vans Old Skool Classic",
    price: 64.99,
    originalPrice: 80.0,
    category: "footwear",
    sellerId: 3,
    seller: "ShoesWorld",
    image:
      "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400&h=300&fit=crop",
    description:
      "Iconic skate shoes with signature side stripe and waffle outsole",
    rating: 4.5,
    reviewCount: 201,
    views: 7800,
    stock: 95,
    brand: "Vans",
    inStock: true,
    stockQuantity: 95,
    discount: 19,
    sales: 201,
    subcategory: "footwear",
    features: [
      "Signature side stripe",
      "Suede and canvas upper",
      "Padded collar",
      "Waffle outsole",
      "Skate-specific design",
      "Lace-up closure",
    ],
    specifications: {
      Upper: "Suede and canvas",
      Sole: "Waffle rubber",
      Closure: "Lace-up",
      Height: "Low-top",
      Weight: "1.0 lbs",
      Style: "Skate/Lifestyle",
    },
  },
  {
    id: 18,
    title: "New Balance 990v5 Made in USA",
    name: "New Balance 990v5 Made in USA",
    price: 184.99,
    originalPrice: 220.0,
    category: "footwear",
    sellerId: 3,
    seller: "ShoesWorld",
    image:
      "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=300&fit=crop",
    description: "Premium made in USA running shoes with superior comfort",
    rating: 4.8,
    reviewCount: 156,
    views: 5400,
    stock: 45,
    brand: "New Balance",
    inStock: true,
    stockQuantity: 45,
    discount: 16,
    sales: 156,
    subcategory: "footwear",
    features: [
      "Made in USA",
      "ENCAP midsole technology",
      "Premium suede and mesh upper",
      "Rubber outsole",
      "Superior comfort",
      "Heritage design",
    ],
    specifications: {
      Midsole: "ENCAP polyurethane",
      Upper: "Suede and mesh",
      Outsole: "Blown rubber",
      Drop: "12mm",
      Weight: "11.2 oz",
      "Made in": "USA",
    },
  },
  {
    id: 19,
    title: "Puma RS-X Reinvention",
    name: "Puma RS-X Reinvention",
    price: 119.99,
    originalPrice: 140.0,
    category: "footwear",
    sellerId: 3,
    seller: "ShoesWorld",
    image:
      "https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=400&h=300&fit=crop",
    description:
      "Retro-futuristic sneakers with bold colorways and chunky silhouette",
    rating: 4.3,
    reviewCount: 167,
    views: 6200,
    stock: 70,
    brand: "Puma",
    inStock: true,
    stockQuantity: 70,
    discount: 14,
    sales: 167,
    subcategory: "footwear",
    features: [
      "Running System technology",
      "Mesh and synthetic upper",
      "Chunky midsole",
      "Bold colorways",
      "Retro-futuristic design",
      "Comfortable fit",
    ],
    specifications: {
      Upper: "Mesh and synthetic",
      Midsole: "EVA foam",
      Outsole: "Rubber",
      Closure: "Lace-up",
      Weight: "1.3 lbs",
      Style: "Lifestyle/Training",
    },
  },

  // HomeGoods Products (sellerId: 4) - 5 products
  {
    id: 20,
    title: "Ninja Coffee Maker Pro",
    name: "Ninja Coffee Maker Pro",
    price: 89.99,
    originalPrice: 120.0,
    category: "appliances",
    sellerId: 4,
    seller: "HomeGoods",
    image:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=300&fit=crop",
    description: "Automatic coffee brewing machine with multiple brew sizes",
    rating: 4.5,
    reviewCount: 234,
    views: 9800,
    stock: 30,
    brand: "Ninja",
    inStock: true,
    stockQuantity: 30,
    discount: 25,
    sales: 234,
    subcategory: "appliances",
    features: [
      "Multiple brew sizes",
      "Auto-iQ one-touch intelligence",
      "Thermal flavor extraction",
      "Glass carafe",
      "Built-in frother",
      "Programmable delay brew",
    ],
    specifications: {
      Capacity: "10-cup glass carafe",
      "Brew Sizes": "6 sizes (6oz to 12oz)",
      "Water Reservoir": "50oz removable",
      Dimensions: "11.8 x 9.8 x 14.2 inches",
      Power: "1000W",
      Warranty: "1 year",
    },
  },
  {
    id: 21,
    title: "KitchenAid Artisan Stand Mixer",
    name: "KitchenAid Artisan Stand Mixer",
    price: 349.99,
    originalPrice: 429.99,
    category: "appliances",
    sellerId: 4,
    seller: "HomeGoods",
    image:
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop",
    description: "Professional 5-quart stand mixer for all your baking needs",
    rating: 4.9,
    reviewCount: 189,
    views: 7200,
    stock: 15,
    brand: "KitchenAid",
    inStock: true,
    stockQuantity: 15,
    discount: 19,
    sales: 189,
    subcategory: "appliances",
    features: [
      "5-quart stainless steel bowl",
      "10-speed slide control",
      "Tilt-head design",
      "Planetary mixing action",
      "Power hub for attachments",
      "Metal construction",
    ],
    specifications: {
      "Bowl Capacity": "5 quarts",
      Speeds: "10",
      Motor: "325 watts",
      Dimensions: "14 x 8.7 x 14 inches",
      Weight: "22 lbs",
      Warranty: "1 year",
    },
  },
  {
    id: 22,
    title: "Dyson V15 Detect Cordless Vacuum",
    name: "Dyson V15 Detect Cordless Vacuum",
    price: 549.99,
    originalPrice: 649.99,
    category: "cleaning",
    sellerId: 4,
    seller: "HomeGoods",
    image:
      "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=300&fit=crop",
    description: "Cordless stick vacuum with laser dust detection technology",
    rating: 4.7,
    reviewCount: 145,
    views: 6100,
    stock: 25,
    brand: "Dyson",
    inStock: true,
    stockQuantity: 25,
    discount: 15,
    sales: 145,
    subcategory: "cleaning",
    features: [
      "Laser dust detection",
      "60 minutes runtime",
      "Powerful suction",
      "HEPA filtration",
      "LCD screen",
      "Multiple attachments",
    ],
    specifications: {
      Runtime: "Up to 60 minutes",
      Suction: "240 AW",
      Filtration: "HEPA",
      Weight: "2.6 kg",
      "Dust Bin": "0.76L",
      "Charging Time": "4.5 hours",
    },
  },
  {
    id: 23,
    title: "Le Creuset Dutch Oven 5.5qt",
    name: "Le Creuset Dutch Oven 5.5qt",
    price: 279.99,
    originalPrice: 350.0,
    category: "cookware",
    sellerId: 4,
    seller: "HomeGoods",
    image:
      "https://images.unsplash.com/photo-1556909114-54c7b7fd8636?w=400&h=300&fit=crop",
    description: "Enameled cast iron Dutch oven for slow cooking and braising",
    rating: 4.8,
    reviewCount: 98,
    views: 4200,
    stock: 20,
    brand: "Le Creuset",
    inStock: true,
    stockQuantity: 20,
    discount: 20,
    sales: 98,
    subcategory: "cookware",
    features: [
      "Enameled cast iron construction",
      "5.5-quart capacity",
      "Oven safe to 500°F",
      "Tight-fitting lid",
      "Easy-to-clean interior",
      "Lifetime warranty",
    ],
    specifications: {
      Capacity: "5.5 quarts",
      Material: "Enameled cast iron",
      "Oven Safe": "Up to 500°F",
      Dimensions: "10.25 x 10.25 x 4.5 inches",
      Weight: "12.8 lbs",
      "Dishwasher Safe": "Yes",
    },
  },
  {
    id: 24,
    title: "Instant Pot Duo 7-in-1",
    name: "Instant Pot Duo 7-in-1",
    price: 99.99,
    originalPrice: 129.99,
    category: "appliances",
    sellerId: 4,
    seller: "HomeGoods",
    image:
      "https://images.unsplash.com/photo-1585515656071-f36df0c11b88?w=400&h=300&fit=crop",
    description:
      "Multi-functional electric pressure cooker with 7 appliances in 1",
    rating: 4.6,
    reviewCount: 567,
    views: 12400,
    stock: 45,
    brand: "Instant Pot",
    inStock: true,
    stockQuantity: 45,
    discount: 23,
    sales: 567,
    subcategory: "appliances",
    features: [
      "7-in-1 functionality",
      "6-quart capacity",
      "14 smart programs",
      "Stainless steel inner pot",
      "Steam rack included",
      "Easy-seal lid",
    ],
    specifications: {
      Capacity: "6 quarts",
      Functions: "7 (Pressure, Slow, Rice, Yogurt, Steam, Sauté, Warm)",
      Programs: "14 smart programs",
      Pressure: "High/Low",
      Dimensions: "13 x 12.5 x 12.5 inches",
      Power: "1000W",
    },
  },

  // PhotoPro Products (sellerId: 5) - 6 products
  {
    id: 25,
    title: "Canon EOS R6 Mark II",
    name: "Canon EOS R6 Mark II",
    price: 2499.99,
    originalPrice: 2699.99,
    category: "cameras",
    sellerId: 5,
    seller: "PhotoPro",
    image:
      "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=300&fit=crop",
    description: "Professional mirrorless camera with 4K 60p video recording",
    rating: 4.9,
    reviewCount: 87,
    views: 3200,
    stock: 15,
    brand: "Canon",
    inStock: true,
    stockQuantity: 15,
    discount: 7,
    sales: 87,
    subcategory: "cameras",
    features: [
      "24.2MP full-frame CMOS sensor",
      "4K 60p video recording",
      "Dual Pixel CMOS AF II",
      "5-axis image stabilization",
      "Weather-sealed design",
      "Dual card slots",
    ],
    specifications: {
      Sensor: "24.2MP full-frame CMOS",
      Video: "4K 60p",
      Autofocus: "Dual Pixel CMOS AF II",
      Stabilization: "5-axis IBIS",
      Connectivity: "WiFi, Bluetooth",
      Battery: "LP-E6NH",
    },
  },
  {
    id: 26,
    title: "Sony Alpha A7 IV",
    name: "Sony Alpha A7 IV",
    price: 2299.99,
    originalPrice: 2499.99,
    category: "cameras",
    sellerId: 5,
    seller: "PhotoPro",
    image:
      "https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=400&h=300&fit=crop",
    description:
      "Full-frame mirrorless camera with 33MP sensor and real-time tracking",
    rating: 4.8,
    reviewCount: 76,
    views: 2800,
    stock: 12,
    brand: "Sony",
    inStock: true,
    stockQuantity: 12,
    discount: 8,
    sales: 76,
    subcategory: "cameras",
    features: [
      "33MP full-frame sensor",
      "Real-time tracking AF",
      "4K video recording",
      "693 AF points",
      "5-axis stabilization",
      "Dual card slots",
    ],
    specifications: {
      Sensor: "33MP full-frame Exmor R",
      Video: "4K 30p",
      Autofocus: "693 AF points",
      Stabilization: "5-axis",
      ISO: "100-51200",
      Battery: "NP-FZ100",
    },
  },
  {
    id: 27,
    title: "Nikon Z9 Professional",
    name: "Nikon Z9 Professional",
    price: 4999.99,
    originalPrice: 5499.99,
    category: "cameras",
    sellerId: 5,
    seller: "PhotoPro",
    image:
      "https://images.unsplash.com/photo-1606983287719-04cb5d22006c?w=400&h=300&fit=crop",
    description: "Flagship mirrorless camera with 45.7MP sensor and 8K video",
    rating: 4.7,
    reviewCount: 54,
    views: 2100,
    stock: 8,
    brand: "Nikon",
    inStock: true,
    stockQuantity: 8,
    discount: 9,
    sales: 54,
    subcategory: "cameras",
    features: [
      "45.7MP full-frame sensor",
      "8K video recording",
      "120fps continuous shooting",
      "Advanced AF system",
      "Dual CFexpress slots",
      "Weather sealing",
    ],
    specifications: {
      Sensor: "45.7MP full-frame CMOS",
      Video: "8K 30p",
      Burst: "120fps",
      Autofocus: "493 AF points",
      Storage: "Dual CFexpress Type B",
      Battery: "EN-EL18d",
    },
  },
  {
    id: 28,
    title: "Canon RF 70-200mm f/2.8L IS USM",
    name: "Canon RF 70-200mm f/2.8L IS USM",
    price: 1899.99,
    originalPrice: 2099.99,
    category: "cameras",
    sellerId: 5,
    seller: "PhotoPro",
    image:
      "https://images.unsplash.com/photo-1606983340200-7990c7cddc7b?w=400&h=300&fit=crop",
    description: "Professional telephoto zoom lens with Image Stabilization",
    rating: 4.9,
    reviewCount: 43,
    views: 1800,
    stock: 6,
    brand: "Canon",
    inStock: true,
    stockQuantity: 6,
    discount: 10,
    sales: 43,
    subcategory: "cameras",
    features: [
      "70-200mm telephoto zoom",
      "f/2.8 constant aperture",
      "Image Stabilization",
      "Weather sealing",
      "Ultra-low dispersion glass",
      "Nano USM motor",
    ],
    specifications: {
      "Focal Length": "70-200mm",
      Aperture: "f/2.8",
      "Image Stabilization": "5 stops",
      "Min Focus": "0.7m",
      Weight: "1070g",
      Filter: "77mm",
    },
  },
  {
    id: 29,
    title: "Manfrotto MT190XPRO4 Tripod",
    name: "Manfrotto MT190XPRO4 Tripod",
    price: 399.99,
    originalPrice: 499.99,
    category: "cameras",
    sellerId: 5,
    seller: "PhotoPro",
    image:
      "https://images.unsplash.com/photo-1606983287851-4c74e2a6dd2b?w=400&h=300&fit=crop",
    description: "Professional aluminum tripod with 90° column mechanism",
    rating: 4.6,
    reviewCount: 67,
    views: 2400,
    stock: 18,
    brand: "Manfrotto",
    inStock: true,
    stockQuantity: 18,
    discount: 20,
    sales: 67,
    subcategory: "cameras",
    features: [
      "Aluminum construction",
      "90° column mechanism",
      "4-section legs",
      "Quick Power Lock",
      "Bubble level",
      "Carrying case included",
    ],
    specifications: {
      Material: "Aluminum",
      "Max Height": "171cm",
      "Min Height": "50cm",
      "Folded Length": "65cm",
      Weight: "2kg",
      "Load Capacity": "7kg",
    },
  },
  {
    id: 30,
    title: "Godox AD600Pro Studio Flash",
    name: "Godox AD600Pro Studio Flash",
    price: 849.99,
    originalPrice: 999.99,
    category: "cameras",
    sellerId: 5,
    seller: "PhotoPro",
    image:
      "https://images.unsplash.com/photo-1551439602-a3cfd7ee0334?w=400&h=300&fit=crop",
    description: "Professional portable studio flash with TTL and HSS",
    rating: 4.7,
    reviewCount: 29,
    views: 1200,
    stock: 10,
    brand: "Godox",
    inStock: true,
    stockQuantity: 10,
    discount: 15,
    sales: 29,
    subcategory: "cameras",
    features: [
      "600Ws studio flash",
      "TTL and HSS support",
      "2.4G wireless system",
      "Fast recycling time",
      "Modeling light",
      "Portable design",
    ],
    specifications: {
      Power: "600Ws",
      "Flash Duration": "1/220s - 1/10000s",
      "Recycling Time": "0.01-2.5s",
      "Modeling Light": "150W LED",
      Battery: "8700mAh",
      Weight: "3kg",
    },
  },
];

export default function handler(req, res) {
  if (req.method === "GET") {
    const { id } = req.query;

    if (id) {
      // Return specific product
      const product = mockProducts.find((p) => p.id === parseInt(id));
      if (product) {
        res.status(200).json({
          success: true,
          data: product,
        });
      } else {
        res.status(404).json({
          success: false,
          error: "Product not found",
        });
      }
    } else {
      // Return all products
      res.status(200).json({
        success: true,
        data: mockProducts,
        total: mockProducts.length,
      });
    }
  } else {
    res.setHeader("Allow", ["GET"]);
    res.status(405).end(`Method ${req.method} Not Allowed`);
  }
}
